
name: ai-session-02
channels:
  - conda-forge
  - damianavila82
  - pytorch
dependencies:
  - python==3.6.7
  - ipython==7.2.0
  - jupyter
  - matplotlib
  - rise
  - numpy==1.15.0
  - pytorch::pytorch==0.4.1
  - pytorch::torchvision==0.2.1
  - pytorch::ignite==0.1.1
